service: critical-css

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

package:
  exclude:
    - README.md
    - .github/**
    - .idea/**

functions:
  processor:
    handler: handler.processor
    timeout: 600
    memorySize: 2048
    maximumEventAge: 600
    maximumRetryAttempts: 0
